export const Riddles = [
  {
    question: "Start!",
    answer: "Press the next button below to start the flashcards :)",
    difficulty: "none",
    image: "https://png.pngtree.com/png-vector/20221123/ourmid/pngtree-game-next-button-in-green-gradient-png-image_6476896.png",
  },
  {
    question: "What can you catch but not throw?",
    answer: "A cold.",
    difficulty: "easy",
    image: "https://static-00.iconduck.com/assets.00/cold-face-emoji-2006x2048-1j861zw3.png",
  },
  {
    question: "What has a neck but no head?",
    answer: "A bottle.",
    difficulty: "medium",
    image: "https://png.pngtree.com/png-vector/20240812/ourmid/pngtree-cold-beer-in-green-bottle-png-image_13458325.png",
  },
  {
    question: "What runs, but never walks, has a bed but never sleeps, and has a mouth but never eats?",
    answer: "A river.",
    difficulty: "medium",
    image: "https://clipart-library.com/img1/1499332.png",
  },
  {
    question: "I have cities, but no houses. Forests, but no trees. Rivers, but no water. What am I?",
    answer: "A map.",
    difficulty: "hard",
    image: "https://cdn3d.iconscout.com/3d/premium/thumb/map-3d-illustration-download-in-png-blend-fbx-gltf-file-formats--location-pin-navigation-gps-camping-pack-adventure-and-illustrations-4051621.png?f=webp",
  },
  {
    question: "What has keys but can’t open locks?",
    answer: "A piano.",
    difficulty: "easy",
    image: "https://www.freepnglogos.com/uploads/piano-png/piano-music-png-only-13.png",
  },
  {
    question: "What gets wetter the more it dries?",
    answer: "A towel.",
    difficulty: "easy",
    image: "https://pngimg.com/d/towel_PNG76.png",
  },
  {
    question: "I am not alive, but I grow. I don’t have lungs, but I need air. What am I?",
    answer: "Fire.",
    difficulty: "hard",
    image: "https://png.pngtree.com/png-vector/20230912/ourmid/pngtree-illustration-of-a-fire-png-image_10023811.png",
  },
  {
    question: "What belongs to you but is used more by others?",
    answer: "Your name.",
    difficulty: "medium",
    image: "https://images.fineartamerica.com/images/artworkimages/medium/3/name-badge-vector-tim-hester-transparent.png",
  },
  {
    question: "What has hands but can’t clap?",
    answer: "A clock.",
    difficulty: "easy",
    image: "https://freepngimg.com/thumb/clock/54-clock-png-image.png",
  },
  {
    question: "The more you take away from me, the bigger I get. What am I?",
    answer: "A hole.",
    difficulty: "medium",
    image: "https://www.pngall.com/wp-content/uploads/4/Hole-PNG-Free-Download.png",
  },
  {
    question: "What has to be broken before you can use it?",
    answer: "An egg.",
    difficulty: "easy",
    image: "https://freepngimg.com/thumb/egg/7-2-egg-png.png",
  },
  {
    question: "What has many teeth but cannot bite?",
    answer: "A comb.",
    difficulty: "medium",
    image: "https://pngimg.com/d/comb_PNG124.png",
  },
  {
    question: "What invention lets you look right through a wall?",
    answer: "A window.",
    difficulty: "easy",
    image: "https://png.pngtree.com/png-vector/20231115/ourmid/pngtree-white-window-opened-to-the-sky-glass-png-image_10526770.png",
  },
  {
    question: "What has one eye but can’t see?",
    answer: "A needle.",
    difficulty: "hard",
    image: "https://pngimg.com/d/sewing_needle_PNG103099.png",
  },
  {
    question: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?",
    answer: "An echo.",
    difficulty: "hard",
    image: "https://www.namm.org/sites/default/files/styles/promo/public/2023-03/namm-communities-pro-audio-live-sound.png?itok=By4wBL6-",
  },
  {
    question: "What begins with T, ends with T, and has T in it?",
    answer: "A teapot.",
    difficulty: "medium",
    image: "https://static.vecteezy.com/system/resources/previews/047/834/726/non_2x/white-porcelain-teapot-on-transparent-background-free-png.png",
  },
  {
    question: "I’m tall when I’m young and short when I’m old. What am I?",
    answer: "A candle.",
    difficulty: "medium",
    image: "https://png.pngtree.com/png-clipart/20230124/ourmid/pngtree-mourning-candle-png-image_6568463.png",
  },
  {
    question: "What comes down but never goes up?",
    answer: "Rain.",
    difficulty: "hard",
    image: "https://static.vecteezy.com/system/resources/previews/053/715/524/non_2x/blue-umbrella-with-rain-drops-isolated-on-transparent-background-symbolizing-protection-and-rainy-weather-in-a-refreshing-illustration-png.png",
  },
  {
    question: "You see a boat filled with people, yet there isn’t a single person on board. How is that possible?",
    answer: "All the people are married.",
    difficulty: "hard",
    image: "https://cdn-icons-png.flaticon.com/512/3366/3366568.png",
  },
  {
    question: "What has a head and a tail but no body?",
    answer: "A coin.",
    difficulty: "easy",
    image: "https://www.royalmint.com/globalassets/stories/2023/november/3-edward_viii-1200x600.png",
  },
  {
    question: "The more you take, the more you leave behind. What are they?",
    answer: "Footsteps.",
    difficulty: "medium",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Footsteps_icon.svg/1200px-Footsteps_icon.svg.png",
  },
  {
    question: "What has branches, but no fruit, trunk, or leaves. What am I?",
    answer: "A bank.",
    difficulty: "medium",
    image: "https://pngimg.com/d/bank_PNG24.png",
  },
  {
    question: "What can fill a room but takes up no space?",
    answer: "Light.",
    difficulty: "easy",
    image: "https://www.iconpacks.net/icons/2/free-bulb-icon-3662-thumb.png",
  },
  {
    question: "What can travel around the world while staying in the same corner?",
    answer: "A stamp.",
    difficulty: "hard",
    image: "https://pngimg.com/d/postage_stamp_PNG25.png",
  }
]